Question 1

In [4]:
import numpy as np
a=np.arange(2,50,3)
print(a)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


Question 2

In [3]:
import numpy as np
list1=[]
list2=[]

for i in range(5):
    n=int(input())
    list1.append(n)
    a=np.array(list1)

for j in range(5):
    m=int(input())
    list2.append(m)
    b=np.array(list2)

concat_arr=np.concatenate((a,b))
sort_arr=np.sort(concat_arr)
print (sort_arr)

5
54
98
41
56
253
77
256
45
85
[  5  41  45  54  56  77  85  98 253 256]


Question 3

In [7]:
import numpy as np
a=np.array([[1,3,5],[2,4,6]])
print (a)
print(a.ndim)
print(a.size)

[[1 3 5]
 [2 4 6]]
2
6


Question 4

We can use reshape() function to reshape a 1D array to 2D array. 

In [29]:
import numpy as np
a=np.array([2,4,6,8])
print("1D array: \n", a)
#print(a)
#print('\n')
print("2D array: \n", a.reshape(2,2))
#a.reshape(2,2)

1D array: 
 [2 4 6 8]
2D array: 
 [[2 4]
 [6 8]]


Question 5

In [2]:
import numpy as np
a=np.array([[1,3],[5,7]])
b=np.array([[2,4],[6,8]])
print("Vertical stacking:\n", np.vstack((a, b))) 
print("Horzontal stacking:\n", np.hstack((a, b))) 

Vertical stacking:
 [[1 3]
 [5 7]
 [2 4]
 [6 8]]
Horzontal stacking:
 [[1 3 2 4]
 [5 7 6 8]]


Question 6

In [27]:
import numpy as np
a=np.array([1,2,2,3,4,5,6,6,7,9,11,3,4])
b=np.unique(a)

print("Unique Elements: ",b)
print("Count of unique elements: ",len(b))


Unique Elements:  [ 1  2  3  4  5  6  7  9 11]
Count of unique elements:  9
